BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "RPG_ID" (
	"FANTASY"	NUMERIC DEFAULT 1,
	"MODERN"	NUMERIC DEFAULT 2,
	"MILITARY"	NUMERIC DEFAULT 3,
	"FUTURISTIC"	NUMERIC DEFAULT 4,
	"MEDIEVAL"	NUMERIC DEFAULT 5
);
COMMIT;
